### ISSUE TITLE
quick bug fix on tag.ejs

### ISSUE THREAD

**Issue by Digi-D** [yzzting/hexo-theme-MyFairLady#2]
in layout/_partial/post/tag.ejs 

IF is missing in --> 

```<% (post.tags && post.tags.length ){ %>
    <div class="article-tag">
        <%- list_tags(post.tags,{
            show_count:false,
            class:'article-tag'
        }) %>
    </div>
<% } %>

```

slightly blows up the generation process :) If you want, can submit a formal pull request but as I already started hacking in a slightly different direction from your original code, this seemed like an easier path :) 

Thank you, for putting together a great theme!
```

**Comment by yzzting** [comment]
@Digi-D 
Hey I would like to say sorry . now you just wait until reply. I've fix the bug page tag.ejs.  

If you have any thoughts can continue to exchange

**Comment by Digi-D** [comment]
np. this is why we make projects open source :) No thoughts at this point. Will reach out if I have any, thank you again
