### ISSUE TITLE
部署主题后，本地访问发现scss样式没有加载，是不是缺少一些其它配置需要修改

### ISSUE THREAD

**Issue by zuwensong** [yzzting/hexo-theme-MyFairLady#3]
step 1 : git clone 到themes下 改名为blog
step 2 : 修改hexo下_config.yml参数：theme: blog
step 3 : hexo c     hexo g      hexo s然后访问localhost:4000
result : 显示了主题内容，但是scss样式并没有生效
是不是我这边缺少修改一些参数？

**Comment by zuwensong** [comment]
缺少安装cnpm install hexo-renderer-sass --save

**Comment by yzzting** [comment]
我在文档里面有写,可能我写的不够详细@zuwensong

**Comment by zuwensong** [comment]
没有把主题颜色生效呢，显示的颜色是黑色的修改主题下面的_config.yml里的blog_color也不起作用，请问？ @yzzting

**Comment by yzzting** [comment]
@zuwensong 你是指在主题的_config.yml修改颜色值吗？ 我只是提供了4种不同的颜色.如果你想要别的颜色 你要到MyFairLady\source\sass\common\color.scss 去修改

**Comment by zuwensong** [comment]
不是，是主题自带的颜色没有生效。知道可能是哪种原因导致的吗，原谅我看现在的前端代码越来越头疼 @yzzting

**Comment by yzzting** [comment]
可能是_config.yml没写对 你能截个图吗@zuwensong

**Comment by zuwensong** [comment]
![image](https://cloud.githubusercontent.com/assets/18671875/20953875/7e12fd38-bc71-11e6-9fc1-cbf5e0c0ee75.png)
![image](https://cloud.githubusercontent.com/assets/18671875/20953900/9d758812-bc71-11e6-9225-7faa12e49cad.png)

**Comment by zuwensong** [comment]
@yzzting

**Comment by yzzting** [comment]
`# Blog main color
# Default | Mint Green | Pale Denim | Hot Pink | Dark Violet
blog-color: Mint Green

# Blog code theme
# Default | Night | Eighties | Blue | Bright
code-theme: Default

我的是这样是有效果的

或者用npm重装一次hexo-renderer-scss 看看效果`

**Comment by yzzting** [comment]
`# Blog main color
# Default | Mint Green | Pale Denim | Hot Pink | Dark Violet
blog-color: Mint Green

# Blog code theme
# Default | Night | Eighties | Blue | Bright
code-theme: Default
`

我的是这样是有效果的

或者用npm重装一次hexo-renderer-scss 看看效果`

@zuwensong

**Comment by zuwensong** [comment]
hi~,刚发现颜色未生效是在color.scss下面的这行代码未获取到值：
$theme-color-config: hexo-theme-config('blog-color');
请问hexo-theme-config('blog-color')这个函数是在哪定义的，我全局检索没有搜到它.
@yzzting

**Comment by yzzting** [comment]
这是hexo--renderer-scss插件的函数 用来获取_config.yml文件里的blog-color 你要装的是hexo--renderer-scss
@zuwensong

**Comment by zuwensong** [comment]
ok,下班回去我再试试，ths, boy.
